### PR TITLE
Add trigger Campaign method

### PR DESCRIPTION
**Pull request by FabriceGaudin**
Handle the REST API method to trigger a campaign for an array of leads, with an array of optional tokens.

### CODE REVIEW

**Comment by FabriceGaudin** [comment]
Hello, any update ?

**Comment by peaches** [comment]
Hey, there's now a conflict because I merged #11, which also added the Campaign object. It's a simple resolution since most of the changes you have are independent of the other PR.

**Comment by peaches** [comment]
Oh, I misread. trigger and request campaigns are the same thing.

**Comment by peaches** [comment]
Does the other API work for you? Once you confirm yes/no, I'll cut another release.

**Comment by FabriceGaudin** [comment]
Yes the other works perfectly as well.

**Comment by peaches** [comment]
I'll close this one as a dupe then, thanks for your work though.

**Pull request closed without merging**
